export const mockTasks = [
    {
      id: 1,
      title: 'Create Wireframes',
      description: 'Design wireframes for the new website.',
      projectId: 1,
      assignedTo: 1,
      status: 'In Progress',
      priority: 'High',
      deadline: '2023-10-20',
    },
    {
      id: 2,
      title: 'Develop Homepage',
      description: 'Code the homepage layout.',
      projectId: 1,
      assignedTo: 2,
      status: 'To Do',
      priority: 'Medium',
      deadline: '2023-10-25',
    },
    {
      id: 3,
      title: 'Test Mobile App',
      description: 'Test the mobile app on iOS and Android.',
      projectId: 2,
      assignedTo: 1,
      status: 'To Do',
      priority: 'High',
      deadline: '2023-11-01',
    },
  ];